### ISSUE TITLE
csv-table align option is ignored

### ISSUE THREAD

**Issue by ghisvail** [amedama41/sphinx-docxbuilder#7]
The `csv-table` directive always produce a table with left-aligned cells, regardless of the `:align:` option being set to `center` or `right`. I would expect the resulting table to respect the alignement option attached with the `csv-table` directive, and default to left if none is provided.

**Comment by amedama41** [comment]
As far as I know, `:align:` option does not have effect for cell alignment also in other builders.
In my opinion, this is a job of a style file.
I will add the feature to apply different style for each tables in next release.

**Comment by ghisvail** [comment]
> I will add the feature to apply different style for each tables in next release.

I'd be happy to work on it, if you accept contributions.

Could you point me towards a place to start in the code base?

**Comment by amedama41** [comment]
@ghisvail 

I add the feature to apply user defined style in docxbuilder 1.2.0.
Please update docxbuilder.
See documents (https://docxbuilder.readthedocs.io/en/latest/customization.html#user-defined-styles) for details
