### ISSUE TITLE
Image style are not applied

### ISSUE THREAD

**Issue by gvcgael** [amedama41/sphinx-docxbuilder#9]
All the images have a standard `paragraph` style.

Do you reproduce the same problem ? Any idea what could be the cause ? 

Thanks

**Comment by amedama41** [comment]
"Figure" paragraph style is applied to only images generated by `figure` directive.
Docxbuilder applies a standard paragraph style to images generated by `image` directive.

Which directive do you use?

**Comment by gvcgael** [comment]
I'm using [recommonmark](https://recommonmark.readthedocs.io/en/latest/index.html) to generate files from markdown. I suppose that it generates an `image` directive. How can I workaround this ? 

Thanks !

**Comment by amedama41** [comment]
@gvcgael 

I add "Image" paragraph style for image directive in docxbuilder 1.2.0.
Please use this style.

**Comment by Insoleet** [comment]
Woa perfect, thanks a lot !

**Comment by gvcgael** [comment]
Perfect, thanks a lot !
